package com.example.scene;

public enum SceneName {
    PALETTES, PACKAGES, PRODUCTS, EMAILS, ADMINS, PALETTE_PRODUCT, PACKAGING_PRODUCT, WEIGHINGS, SCAN_PAGE,
    PALETTE_PICK, PACKAGING_PICK, CONFIRMATION, WRONG_WEIGHING, CORRECT_WEIGHING, ADMIN_MAIN_MENU, NOTIFICATIONS, NOTIFICATION
}